# cspell:disable

name: Build frontend image

on:
  push:
  workflow_dispatch:

jobs:
  build-frontend-image:
    name: Build frontend docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/nilscox/shakala-frontend:latest
          file: packages/5-frontend-client/Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
