name: CI

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read

jobs:
  typecheck:
    name: Types check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      maildev:
        image: maildev/maildev

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm test
        env:
          DATABASE_HOST: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: tests
          MAILDEV_HOST: maildev
          MAILDEV_SMTP_PORT: 1025
          MAILDEV_API_PORT: 1080

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm typecheck
      - run: pnpm lint

  spellcheck:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm add -g cspell @cspell/dict-fr-fr
      - run: cspell link add @cspell/dict-fr-fr
      - run: pnpm spellcheck
